language: c

env:
   - BUILD_TYPE=Debug
   - BUILD_TYPE=Release

before_install:
  # Hijacking the crystfel repos for OpenCL headers and ICD
  - sudo add-apt-repository ppa:valmar-lp/crystfel-releases -y
  - sudo apt-get update -qq -y
  - sudo apt-get install opencl-headers ocl-icd-opencl-dev libjson-glib-dev libzmq3-dev autoconf-archive

before_script:
  # Configure with Autotools
  - ./autogen.sh
  - ./configure

  # Configure with CMake
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWITH_GIR=OFF -DWITH_GTK_DOC=OFF -DWITH_PYTHON=OFF

script:
  # Build with Autotools
  - cd ..
  - make

  # Build with CMake
  - cd build
  - make
  - ./tests/test-suite -p /no-opencl
